[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flowswap = "EyfmRhE4D7vEEQGkqW1hAstWC185ZUWr3ERGPv4g37Q2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
